// src/lib/components/shared/sign-out-button.svelte
<script lang="ts" module>
	import type { ButtonProps } from '$lib/components/ui/button';

	export type SignOutButtonProps = ButtonProps & {
		withLabel?: boolean;
	};
</script>

<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { LogOutIcon } from '@lucide/svelte';

	import { goto, invalidateAll } from '$app/navigation';
	import { authClient } from '$lib/auth-client';
	import { Button } from '$lib/components/ui/button';
	import { cn } from '$lib/utils';

	let {
		withLabel,
		variant = 'ghost',
		size = 'default',
		class: className,
		children,
		...restProps
	}: SignOutButtonProps = $props();

	const handleSignOut = async () => {
		await authClient.signOut();
		await invalidateAll();
		toast.success('Signed out successfully');
		await goto('/');
	};
</script>

<Button
	{variant}
	{size}
	class={cn('cursor-pointer', className)}
	onclick={handleSignOut}
	{...restProps}
>
	<LogOutIcon />
	{#if withLabel}Sign out{/if}
</Button>

// src/components/shared/sign-out-button.tsx
import React from 'react'

import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useRouter } from '@tanstack/react-router'

import { LogOutIcon } from 'lucide-react'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { authClient } from '@/lib/auth-client'
import { cn } from '@/lib/utils'

type SignOutButtonProps = React.ComponentProps<'button'> & {
    withLabel?: boolean
    variant?: 'ghost' | 'outline'
}

export function SignOutButton({ withLabel = false, variant = 'ghost', className }: SignOutButtonProps) {
    const navigate = useNavigate()
    const router = useRouter()
    const queryClient = useQueryClient()

    const signOutMutation = useMutation({
        mutationFn: async () => {
            await authClient.signOut()
        },
        onSuccess: () => {
            queryClient.invalidateQueries()
            router.invalidate()
            navigate({ to: '/' })
        },
    })

    const handleSignOut = async () => {
        toast.promise(signOutMutation.mutateAsync(), {
            loading: 'Signing out...',
            success: 'You have been signed out',
            error: 'Failed to sign out. Please try again.',
        })
    }

    return (
        <Button
            variant={variant}
            size="sm"
            onClick={handleSignOut}
            disabled={signOutMutation.isPending}
            className={cn('cursor-pointer', className)}
        >
            <LogOutIcon />
            {withLabel && 'Log out'}
        </Button>
    )
}
