// src/lib/components/auth/sign-out-button.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { LogOutIcon } from '@lucide/svelte';

	import { signout } from '$lib/api/auth.remote';
	import { Button } from '$lib/components/ui/button';
	import { cn } from '$lib/utils';

	interface SignOutButtonProps {
		withLabel?: boolean;
		variant?: 'ghost' | 'outline' | 'destructive';
		size?: 'sm' | 'lg';
		class?: string;
	}

	let {
		withLabel = false,
		variant = 'ghost',
		size = 'sm',
		class: className
	}: SignOutButtonProps = $props();
</script>

<form
	{...signout.enhance(async ({ form, data, submit }) => {
		try {
			await submit();
			form.reset();

			toast.success('Successfully signed out!');
		} catch (error) {
			toast.error('Oh no! Something went wrong');
		}
	})}
>
	<Button
		{variant}
		{size}
		type="submit"
		disabled={!!signout.pending}
		class={cn('cursor-pointer', className)}
	>
		<LogOutIcon />
		{#if withLabel}
			<span>Sign Out</span>
		{/if}
	</Button>
</form>

// src/components/shared/sign-out-button.tsx
import React from 'react'

import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useRouter } from '@tanstack/react-router'

import { LogOutIcon } from 'lucide-react'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { authClient } from '@/lib/auth-client'
import { cn } from '@/lib/utils'

type SignOutButtonProps = React.ComponentProps<'button'> & {
    withLabel?: boolean
    variant?: 'ghost' | 'outline'
}

export function SignOutButton({ withLabel = false, variant = 'ghost', className }: SignOutButtonProps) {
    const navigate = useNavigate()
    const router = useRouter()
    const queryClient = useQueryClient()

    const signOutMutation = useMutation({
        mutationFn: async () => {
            await authClient.signOut()
        },
        onSuccess: () => {
            queryClient.invalidateQueries()
            router.invalidate()
            navigate({ to: '/' })
        },
    })

    const handleSignOut = async () => {
        toast.promise(signOutMutation.mutateAsync(), {
            loading: 'Signing out...',
            success: 'You have been signed out',
            error: 'Failed to sign out. Please try again.',
        })
    }

    return (
        <Button
            variant={variant}
            size="sm"
            onClick={handleSignOut}
            disabled={signOutMutation.isPending}
            className={cn('cursor-pointer', className)}
        >
            <LogOutIcon />
            {withLabel && 'Log out'}
        </Button>
    )
}
