// src/routes/(dashboard)/cabins/cabins-table-actions.svelte
<script lang="ts">
	import { EyeIcon, MoreHorizontalIcon, TrashIcon } from 'lucide-svelte';

	import { Button } from '$lib/components/ui/button';
	import * as Dropdown from '$lib/components/ui/dropdown-menu';

	export let id: string;
</script>

<Dropdown.Root>
	<Dropdown.Trigger asChild let:builder>
		<Button variant="ghost" size="sm" builders={[builder]}>
			<MoreHorizontalIcon class="size-4" />
		</Button>
	</Dropdown.Trigger>

	<Dropdown.Content>
		<Dropdown.Label>Actions</Dropdown.Label>
		<Dropdown.Separator />

		<Dropdown.Item href={`cabins/${id}`}>
			<EyeIcon class="mr-2 size-4" />
			View Details
		</Dropdown.Item>

		<form
			method="POST"
			on:submit={(e) =>
				!confirm('Are you sure you want to delete this? This action cannot be undone') &&
				e.preventDefault()}
		>
			<input type="hidden" name="id" value={id} />

			<Dropdown.Item>
				<button
					type="submit"
					class="flex cursor-default items-center gap-0.5 text-destructive"
				>
					<TrashIcon class="mr-2 size-4" />
					Delete
				</button>
			</Dropdown.Item>
		</form>
	</Dropdown.Content>
</Dropdown.Root>

// app/components/cabins/cabins-table-actions.tsx
import { Form, Link } from '@remix-run/react';
import { EyeIcon, MoreHorizontalIcon, Trash2Icon } from 'lucide-react';

import { Button } from '~/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger
} from '~/components/ui/dropdown-menu';

interface CabinsTableActionsMenuProps {
	cabinId: number;
}

export function CabinsTableActionsMenu({ cabinId }: CabinsTableActionsMenuProps) {
	return (
		<DropdownMenu>
			<DropdownMenuTrigger asChild>
				<Button variant="ghost" className="size-8 p-0">
					<span className="sr-only">Open Menu</span>
					<MoreHorizontalIcon className="size-4" />
				</Button>
			</DropdownMenuTrigger>

			<DropdownMenuContent align="end">
				<DropdownMenuLabel>Actions</DropdownMenuLabel>
				<DropdownMenuSeparator />

				<DropdownMenuItem asChild className="cursor-pointer">
					<Link to={`/dashboard/cabins/${cabinId}`} className="flex items-center">
						<EyeIcon className="mr-2 size-4" />
						View Details
					</Link>
				</DropdownMenuItem>

				<DropdownMenuItem className="p-0">
					<Form method="POST">
						<input type="hidden" name="cabinID" value={cabinId} />

						<Button
							type="submit"
							variant="ghost"
							name="_action"
							value="delete"
							className="text-destructive inline-flex h-min w-full cursor-pointer px-2 py-1.5 text-left"
						>
							<Trash2Icon className="mr-2 size-4" />
							Delete Cabin
						</Button>
					</Form>
				</DropdownMenuItem>
			</DropdownMenuContent>
		</DropdownMenu>
	);
}
