// src/lib/components/cabins/cabins-table-actions.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { EllipsisIcon, Trash2Icon, EyeIcon } from 'lucide-svelte';

	import * as Dropdown from '$lib/components/ui/dropdown-menu';
	import { Button } from '$lib/components/ui/button';

	export let id: number;
</script>

<Dropdown.Root>
	<Dropdown.Trigger asChild let:builder>
		<Button variant="ghost" builders={[builder]} size="icon" class="relative size-8 p-0">
			<EllipsisIcon class="size-6" />
		</Button>
	</Dropdown.Trigger>

	<Dropdown.Content align="end" class="min-w-[10rem]">
		<Dropdown.Group>
			<Dropdown.Label>Actions</Dropdown.Label>
			<Dropdown.Separator />

			<Dropdown.Item on:click={() => goto('/dashboard/cabins/' + id)} class="cursor-pointer">
				<EyeIcon class="size-4 mr-2" />
				View Cabin
			</Dropdown.Item>

			<form method="POST" action="?/delete">
				<!-- <input type="hidden" name="id" value={id} /> -->

				<Button
					role="menuitem"
					variant="ghost"
					type="submit"
					class="flex w-full justify-start cursor-pointer text-destructive px-2"
				>
					<Trash2Icon class="size-4 mr-2" />
					Delete Cabin
				</Button>
			</form>
		</Dropdown.Group>
	</Dropdown.Content>
</Dropdown.Root>

// app/components/cabins/cabins-table-actions.tsx
import { Form, Link } from '@remix-run/react';
import { EyeIcon, MoreHorizontalIcon, Trash2Icon } from 'lucide-react';

import { Button } from '~/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger
} from '~/components/ui/dropdown-menu';

interface CabinsTableActionsMenuProps {
	cabinId: number;
}

export function CabinsTableActionsMenu({ cabinId }: CabinsTableActionsMenuProps) {
	return (
		<DropdownMenu>
			<DropdownMenuTrigger asChild>
				<Button variant="ghost" className="size-8 p-0">
					<span className="sr-only">Open Menu</span>
					<MoreHorizontalIcon className="size-4" />
				</Button>
			</DropdownMenuTrigger>

			<DropdownMenuContent align="end">
				<DropdownMenuLabel>Actions</DropdownMenuLabel>
				<DropdownMenuSeparator />

				<DropdownMenuItem asChild className="cursor-pointer">
					<Link to={`/dashboard/cabins/${cabinId}`} className="flex items-center">
						<EyeIcon className="mr-2 size-4" />
						View Details
					</Link>
				</DropdownMenuItem>

				<DropdownMenuItem className="p-0">
					<Form method="POST">
						<input type="hidden" name="cabinID" value={cabinId} />

						<Button
							type="submit"
							variant="ghost"
							name="_action"
							value="delete"
							className="text-destructive inline-flex h-min w-full cursor-pointer px-2 py-1.5 text-left"
						>
							<Trash2Icon className="mr-2 size-4" />
							Delete Cabin
						</Button>
					</Form>
				</DropdownMenuItem>
			</DropdownMenuContent>
		</DropdownMenu>
	);
}
