// src/features/newsletter/components/newsletter-form.tsx
import React from 'react'

import { useForm } from '@tanstack/react-form'

import { z } from 'zod'

import { Button } from '@/components/ui/button'
import { Field, FieldError } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Spinner } from '@/components/ui/spinner'

const NewsletterFormSchema = z.object({
    email: z.email(),
})

export function NewsletterForm() {
    const [state, setState] = React.useState<'idle' | 'loading' | 'success' | 'error'>('idle')

    const form = useForm({
        defaultValues: {
            email: '',
        },
        validators: {
            onChangeAsync: NewsletterFormSchema,
            onChangeAsyncDebounceMs: 500,
        },
        onSubmit: async ({ value }) => {
            console.log('🚀 ~ NewsletterForm ~ value:', value)
            setState('loading')

            // TODO: Implement newsletter subscription
        },
    })

    return (
        <>
            <form
                onSubmit={(e) => {
                    e.preventDefault()
                    e.stopPropagation()

                    form.handleSubmit()
                }}
                className="mt-6 flex flex-col gap-1 sm:flex-row"
            >
                <form.Field
                    name="email"
                    children={(field) => (
                        <Field data-invalid={field.state.meta.errors.length > 0} className="w-full">
                            <Input
                                id="email"
                                type="email"
                                placeholder="Enter your email address"
                                aria-invalid={field.state.meta.errors.length > 0}
                                onChange={(e) => field.handleChange(e.target.value)}
                            />
                            {field.state.meta.errors?.map((error) => (
                                <FieldError key={error?.message}>{error?.message}</FieldError>
                            ))}
                        </Field>
                    )}
                />

                <Button type="submit" disabled={state === 'loading'}>
                    {state === 'loading' && <Spinner />}
                    {state === 'loading' ? 'Subscribing...' : 'Subscribe'}
                </Button>
            </form>

            <div className="mt-4 mb-4 rounded-lg px-4 py-2 text-sm text-emerald-500">
                {state === 'success' && 'You have successfully subscribed to our newsletter!'}
            </div>
        </>
    )
}

// src/lib/components/newsletter/newsletter-form.svelte
<script lang="ts">
	import { subscribeToNewsletter } from '$lib/api/newsletter.remote';
	import Typography from '$lib/components/shared/typography.svelte';
	import { Button } from '$lib/components/ui/button';
	import { Field, FieldError, FieldSet } from '$lib/components/ui/field';
	import Input from '$lib/components/ui/input/input.svelte';
	import { NewsletterSubscriberSchema } from '$lib/schemas/newsletter-subscriber';
</script>

<form
	{...subscribeToNewsletter.preflight(NewsletterSubscriberSchema)}
	class="mt-6 flex flex-col gap-2 sm:flex-row"
>
	<FieldSet class="flex-1">
		{@const emailIssues = subscribeToNewsletter.fields.email.issues() ?? []}
		<Field data-invalid={emailIssues.length > 0}>
			<Input
				placeholder="Enter your email address"
				{...subscribeToNewsletter.fields.email.as('email')}
				aria-invalid={emailIssues.length > 0}
			/>
			{#each emailIssues as issue}
				<FieldError>{issue.message}</FieldError>
			{/each}
		</Field>
	</FieldSet>
	<Button type="submit" class="cursor-pointer">Subscribe</Button>
</form>

{#if subscribeToNewsletter.result?.success}
	<Typography variant="body" class="mt-4 mb-4 rounded-lg px-4 py-2 text-sm text-emerald-400">
		You have successfully subscribed to our newsletter!
	</Typography>
{:else if subscribeToNewsletter.result?.error}
	<Typography variant="body" class="mt-4 mb-4 rounded-lg px-4 py-2 text-sm text-destructive">
		{subscribeToNewsletter.result?.error}
	</Typography>
{/if}
