// _old/src/app/admin/cabins/add/page.tsx
import Link from 'next/link';
import { ChevronLeftIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { CabinForm } from '../cabin-form';

export default function AddCabinPage() {
	return (
		<>
			<div className="flex items-center justify-between">
				<div className="space-y-2">
					<Button variant="outline" size="icon" asChild>
						<Link href="/admin/cabins">
							<ChevronLeftIcon className="size-4" />
						</Link>
					</Button>
					<h1 className="text-3xl font-semibold tracking-wide">All Cabins</h1>
				</div>
			</div>

			<div className="mt-6">
				<CabinForm />
			</div>
		</>
	);
}

// src/routes/(dashboard)/cabins/add/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import CabinForm from '../cabin-form.svelte';

	export let data: PageData;
</script>

<div class="flex items-center">
	<h1 class="text-3xl font-bold tracking-wide">Add a New Cabin</h1>
</div>

<p class="text-muted-foreground">Here you can view all cabins and their details.</p>

<hr class="my-6 border-gray-200" />

<div class="pb-10">
	<CabinForm data={data.form} />
</div>
