// src/lib/components/cabins/cabin-card.svelte
<script lang="ts">
	import { ArrowRightIcon, BathIcon, BedIcon, UserIcon } from '@lucide/svelte';

	import aboutImg from '$lib/assets/about-1.webp';
	import { Badge } from '$lib/components/ui/badge';
	import { Item, ItemContent, ItemTitle } from '$lib/components/ui/item';
	import type { Cabin } from '$lib/server/db/schemas/cabins';

	interface CabinCardProps {
		cabin: Cabin;
	}

	let { cabin }: CabinCardProps = $props();
</script>

<a
	href={`/cabins/${cabin.slug}`}
	class="group block rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
>
	<Item
		class="h-full overflow-hidden border border-border/50 bg-background p-0 shadow-sm transition-all duration-300 group-hover:scale-[1.02] group-hover:border-primary/20 hover:shadow-xl"
	>
		<!-- Image Section -->
		<!-- TODO: Use a real cabin image -->
		<div class="relative aspect-[4/3] w-full overflow-hidden">
			<img
				src={aboutImg}
				alt={`${cabin.name} cabin`}
				class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-110"
			/>
			<!-- Gradient Overlay -->
			<div
				class="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100"
			></div>

			<!-- Price Badge -->
			<Badge class="absolute top-3 right-3 rounded-full px-3 py-1.5 shadow-lg backdrop-blur-sm">
				<span class="text-lg font-bold">${cabin.pricePerNight.toFixed(2)}</span>
				<span class="ml-1 text-xs font-normal">/night</span>
			</Badge>
		</div>

		<!-- Content Section -->
		<ItemContent class="flex flex-col gap-4 p-5">
			<!-- Title -->
			<ItemTitle
				class="line-clamp-2 text-xl leading-tight font-bold transition-colors duration-200 group-hover:text-primary"
			>
				{cabin.name}
			</ItemTitle>

			<!-- Amenities Grid -->
			<div class="grid grid-cols-3 gap-3 text-sm text-muted-foreground">
				<div class="flex items-center gap-2">
					<UserIcon class="size-4 shrink-0 text-primary" />
					<span>{cabin.maxGuests} guests</span>
				</div>
				<div class="flex items-center gap-2">
					<BedIcon class="size-4 shrink-0 text-primary" />
					<span>{cabin.beds} beds</span>
				</div>
				<div class="flex items-center gap-2">
					<BathIcon class="size-4 shrink-0 text-primary" />
					<span>{cabin.baths} baths</span>
				</div>
			</div>

			<!-- CTA Section -->
			<div class="mt-auto flex items-center justify-between border-t border-border/50 pt-4">
				<span class="font-semibold text-primary transition-colors group-hover:text-primary/80">
					View Details
				</span>
				<ArrowRightIcon
					class="size-5 text-primary transition-transform duration-200 group-hover:translate-x-1"
				/>
			</div>
		</ItemContent>
	</Item>
</a>

// components/cabin-card.tsx
import type { Route } from 'next';
import Image from 'next/image';
import Link from 'next/link';

import { Bed, BedDouble, MapPin, Users } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { AMENITY_ICON_MAP } from '@/lib/amenity-icons';
import { formatNightlyRate } from '@/lib/money';
import { APP_ROUTES } from '@/lib/routes';

const MAX_VISIBLE_AMENITIES = 4;

type CabinCardCabin = {
    _id: string;
    name: string;
    slug: string;
    location: string;
    nightlyRate: number;
    maxGuests: number;
    bedrooms: number;
    beds: number;
    coverImageUrl: string | null;
    shortDescription: string;
};

type AmenityBadge = { _id: string; name: string };

type CabinCardProps = {
    cabin: CabinCardCabin;
    /** Spec §27's "important amenities" -- omit on a card whose query didn't resolve them. */
    amenities?: AmenityBadge[];
    /** Gold ring + "Featured" badge, for the home page's curated selection. */
    featured?: boolean;
};

export function CabinCard({ cabin, amenities, featured }: CabinCardProps) {
    const visibleAmenities = amenities?.slice(0, MAX_VISIBLE_AMENITIES);
    const hiddenAmenityCount = amenities ? amenities.length - MAX_VISIBLE_AMENITIES : 0;

    return (
        <Card className={featured ? 'overflow-hidden ring-primary/30' : 'overflow-hidden'}>
            <div className='relative -mt-(--card-spacing) aspect-4/3 overflow-hidden rounded-t-xl'>
                <Image
                    src={cabin.coverImageUrl ?? '/assets/placeholder.jpg'}
                    alt=''
                    fill
                    sizes='(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw'
                    className='object-cover'
                />
                {featured && <Badge className='absolute top-3 left-3'>Featured</Badge>}
            </div>
            <CardContent className='flex-1 space-y-3'>
                <div className='flex items-start justify-between gap-2'>
                    <h3 className='font-heading text-lg font-medium'>{cabin.name}</h3>
                    <span className='shrink-0 text-base font-semibold text-primary'>
                        {formatNightlyRate(cabin.nightlyRate)}
                    </span>
                </div>

                <p className='flex items-center gap-1.5 text-sm text-muted-foreground'>
                    <MapPin className='size-3.5 shrink-0' aria-hidden='true' />
                    {cabin.location}
                </p>

                <div className='flex items-center gap-4 text-sm text-muted-foreground'>
                    <span
                        className='flex items-center gap-1.5'
                        aria-label={`${cabin.maxGuests} guests`}
                    >
                        <Users className='size-3.5' aria-hidden='true' />
                        <span aria-hidden='true'>{cabin.maxGuests}</span>
                    </span>
                    <span
                        className='flex items-center gap-1.5'
                        aria-label={`${cabin.bedrooms} bedrooms`}
                    >
                        <BedDouble className='size-3.5' aria-hidden='true' />
                        <span aria-hidden='true'>{cabin.bedrooms}</span>
                    </span>
                    <span className='flex items-center gap-1.5' aria-label={`${cabin.beds} beds`}>
                        <Bed className='size-3.5' aria-hidden='true' />
                        <span aria-hidden='true'>{cabin.beds}</span>
                    </span>
                </div>

                <p className='line-clamp-2 border-t border-border pt-3 text-sm text-muted-foreground/80'>
                    {cabin.shortDescription}
                </p>

                {visibleAmenities && visibleAmenities.length > 0 && (
                    <div className='flex flex-wrap gap-1.5'>
                        {visibleAmenities.map((amenity) => {
                            const Icon = AMENITY_ICON_MAP[amenity.name];

                            return (
                                <span
                                    key={amenity._id}
                                    className='flex items-center gap-1 rounded-full border border-border px-2 py-0.5 text-xs text-muted-foreground'
                                >
                                    {Icon && <Icon className='size-3' aria-hidden='true' />}
                                    {amenity.name}
                                </span>
                            );
                        })}
                        {hiddenAmenityCount > 0 && (
                            <span className='flex items-center rounded-full border border-border px-2 py-0.5 text-xs text-muted-foreground'>
                                +{hiddenAmenityCount} more
                            </span>
                        )}
                    </div>
                )}
            </CardContent>
            <CardFooter>
                <Link
                    href={APP_ROUTES.cabinDetails(cabin.slug) as Route}
                    className='text-sm font-medium text-foreground underline underline-offset-4'
                >
                    View Cabin
                </Link>
            </CardFooter>
        </Card>
    );
}
