// app/components/cabins/cabins-table-actions.tsx
import { Form } from '@remix-run/react';
import { MoreHorizontalIcon, PencilIcon, Trash2Icon } from 'lucide-react';

import { Button } from '~/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger
} from '~/components/ui/dropdown-menu';
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from '~/components/ui/sheet';

interface CabinsTableActionsMenuProps {
	cabinId: number;
}

export function CabinsTableActionsMenu({ cabinId }: CabinsTableActionsMenuProps) {
	return (
		<Sheet>
			<DropdownMenu>
				<DropdownMenuTrigger asChild>
					<Button variant="ghost" className="size-8 p-0">
						<span className="sr-only">Open Menu</span>
						<MoreHorizontalIcon className="size-4" />
					</Button>
				</DropdownMenuTrigger>

				<DropdownMenuContent align="end">
					<DropdownMenuLabel>Actions</DropdownMenuLabel>
					<DropdownMenuSeparator />

					<DropdownMenuItem>
						<SheetTrigger className="flex items-center">
							<PencilIcon className="mr-2 size-4" />
							Edit Cabin
						</SheetTrigger>
					</DropdownMenuItem>

					<DropdownMenuItem className="p-0">
						<Form method="POST">
							<input type="hidden" name="cabinID" value={cabinId} />

							<Button
								type="submit"
								variant="ghost"
								name="_action"
								value="delete"
								className="text-destructive inline-flex h-min w-full cursor-pointer px-2 py-1.5 text-left"
							>
								<Trash2Icon className="mr-2 size-4" />
								Delete Cabin
							</Button>
						</Form>
					</DropdownMenuItem>
				</DropdownMenuContent>
			</DropdownMenu>

			{/* Edit Cabin Sheet Content */}
			<SheetContent>
				<SheetTitle>Edit Cabin</SheetTitle>
			</SheetContent>
		</Sheet>
	);
}

// src/routes/admin/cabins/cabins-table-actions.svelte
<script lang="ts">
	import {
		ClipboardCopyIcon,
		CopyIcon,
		EllipsisIcon,
		PencilRulerIcon,
		Trash2Icon
	} from '@lucide/svelte';

	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import { Button } from '$lib/components/ui/button';
	import { toast } from 'svelte-sonner';

	let { id }: { id: string } = $props();

	function handleCopyId() {
		navigator.clipboard.writeText(id);
		toast('ID Copied to clipboard');
	}
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger>
		{#snippet child({ props })}
			<Button
				{...props}
				variant="ghost"
				size="icon"
				class="relative size-8 cursor-pointer p-0"
			>
				<span class="sr-only">Open Menu</span>
				<EllipsisIcon />
			</Button>
		{/snippet}
	</DropdownMenu.Trigger>

	<DropdownMenu.Content align="end">
		<DropdownMenu.Group>
			<DropdownMenu.Label>Actions</DropdownMenu.Label>

			<DropdownMenu.Separator />

			<DropdownMenu.Item onclick={handleCopyId}>
				<CopyIcon />
				Copy Cabin ID
			</DropdownMenu.Item>

			<DropdownMenu.Item>
				<ClipboardCopyIcon />
				Duplicate Cabin
			</DropdownMenu.Item>

			<DropdownMenu.Item>
				<PencilRulerIcon />
				Edit Cabin
			</DropdownMenu.Item>

			<DropdownMenu.Item class="text-destructive">
				<Trash2Icon class="text-destructive" />
				Delete Cabin
			</DropdownMenu.Item>
		</DropdownMenu.Group>
	</DropdownMenu.Content>
</DropdownMenu.Root>
