// app/components/cabins/cabins-table.tsx
import { ColumnDef } from '@tanstack/react-table';
import { ArrowUpDownIcon } from 'lucide-react';

import { DataTable } from '~/components/ui/data-table';
import { Button } from '~/components/ui/button';
import { Cabin } from '~/lib/schemas/cabins-schemas';
import { formatCurrency } from '~/lib/utils/helpers';
import { CabinsTableActionsMenu } from './cabins-table-actions';

type CabinColumns = Omit<Cabin, 'description' | 'createdAt' | 'updatedAt'>;

const columns: ColumnDef<CabinColumns>[] = [
	{
		accessorKey: 'id',
		header: 'ID'
	},
	{
		accessorKey: 'image',
		header: 'Image',
		cell: ({ row }) => {
			const image = (row.getValue('image') as string) ?? 'https://placehold.co/150x100';

			return (
				<div className="h-16 w-24  overflow-hidden rounded-lg">
					<img src={image} alt="Cabin" width={96} height={54} className="rounded-md object-cover" />
				</div>
			);
		}
	},
	{
		accessorKey: 'name',
		header: ({ column }) => (
			<Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
				Name
				<ArrowUpDownIcon size={16} className="ml-2" />
			</Button>
		)
	},
	{
		accessorKey: 'maxCapacity',
		header: ({ column }) => (
			<Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
				Max Capacity
				<ArrowUpDownIcon size={16} className="ml-2" />
			</Button>
		)
	},
	{
		accessorKey: 'price',
		header: ({ column }) => (
			<Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
				Price (USD)
				<ArrowUpDownIcon size={16} className="ml-2" />
			</Button>
		),
		cell: ({ row }) => {
			const amount = parseFloat(row.getValue('price'));

			return <div className="text-right font-medium">{formatCurrency(amount, 'USD')}</div>;
		}
	},
	{
		accessorKey: 'discountPrice',
		header: ({ column }) => (
			<Button variant="ghost" onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}>
				Discount Price (USD)
				<ArrowUpDownIcon size={16} className="ml-2" />
			</Button>
		),
		cell: ({ row }) => {
			const amount = parseFloat(row.getValue('discountPrice'));

			return <div className="text-accent-foreground text-right font-medium">{formatCurrency(amount, 'USD')}</div>;
		}
	},
	{
		id: 'actions',
		header: 'Actions',
		cell: ({ row }) => {
			const cabinId = row.getValue('id') as number;

			return <CabinsTableActionsMenu cabinId={cabinId} />;
		}
	}
];

interface CabinsTableProps {
	data: CabinColumns[];
}

export function CabinsTable({ data }: CabinsTableProps) {
	return <DataTable columns={columns} data={data} />;
}

// src/routes/admin/cabins/cabins-table.svelte
<script lang="ts">
	import { type ColumnDef } from '@tanstack/table-core';

	import placeholder from '$lib/assets/placeholder.jpg';
	import DataTable from '$lib/components/shared/data-table.svelte';
	import { renderComponent, renderSnippet } from '$lib/components/ui/data-table';
	import { getCabins } from '$lib/data-access/cabins.remote';
	import type { Cabin } from '$lib/types';
	import { formatCurrency } from '$lib/utils';
	import CabinsTableActions from './cabins-table-actions.svelte';
	import { Button } from '$lib/components/ui/button';
	import { ArrowUpDownIcon } from '@lucide/svelte';

	let data = $derived(await getCabins());

	const columns: ColumnDef<Omit<Cabin, 'createdAt' | 'updatedAt'>>[] = [
		{
			id: 'image',
			header: 'Cabin Image',
			cell: () => {
				return renderSnippet(image);
			}
		},
		{
			accessorKey: 'name',
			header: 'Cabin Name'
		},
		{
			accessorKey: 'maxCapacity',
			header: 'Max. Capacity',
			cell: ({ row }) => {
				return renderSnippet(maxCapacity, row.original.maxCapacity);
			}
		},
		{
			accessorKey: 'price',
			header: ({ column }) =>
				renderSnippet(priceHeader, {
					onclick: () => column.toggleSorting()
				}),
			cell: ({ row }) => {
				return renderSnippet(price, row.original.price / 100);
			}
		},
		{
			accessorKey: 'discountPercentage',
			header: 'Discount %',
			cell: ({ row }) => {
				return renderSnippet(discountPercent, row.original.discountPercentage);
			}
		},
		{
			id: 'actions',
			cell: ({ row }) => {
				return renderComponent(CabinsTableActions, { id: row.original.id });
			}
		}
	];
</script>

{#snippet image()}
	<div class="relative h-16 w-24">
		<img
			src={placeholder}
			alt="placeholder"
			width={96}
			height={64}
			class="size-full rounded object-cover"
		/>
	</div>
{/snippet}

{#snippet priceHeader({ onclick }: { onclick: () => void })}
	<Button variant="ghost" {onclick}>
		Price
		<ArrowUpDownIcon />
	</Button>
{/snippet}

{#snippet price(value: number)}
	<div>{formatCurrency(value)}</div>
{/snippet}

{#snippet discountPercent(value: number | null)}
	<div>
		{#if value}
			{value.toFixed(2)}%
		{:else}
			-
		{/if}
	</div>
{/snippet}

{#snippet maxCapacity(value: number)}
	<div>Fits up to {value} guests</div>
{/snippet}

<DataTable
	{data}
	{columns}
	placeholder="Search cabins by name..."
	filterColumn="name"
	showPagination
/>
