// src/app/dashboard/cabins/_components/cabins-table-actions.tsx
'use client';

import { MoreVertical } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import type { Cabin } from '@/database/schemas';

export function CabinsTableActions({ cabin }: { cabin: Omit<Cabin, 'description' | 'updatedAt'> }) {
	return (
		<DropdownMenu>
			<DropdownMenuTrigger asChild>
				<Button variant="ghost" className="size-8 p-0">
					<span className="sr-only">Open menu</span>
					<MoreVertical className="size-4" />
				</Button>
			</DropdownMenuTrigger>
			<DropdownMenuContent align="end">
				<DropdownMenuLabel>Actions</DropdownMenuLabel>
				<DropdownMenuItem
				//   onClick={() => navigator.clipboard.writeText(payment.id)}
				>
					Copy payment ID
				</DropdownMenuItem>
				<DropdownMenuSeparator />
				<DropdownMenuItem>View customer</DropdownMenuItem>
				<DropdownMenuItem>View payment details</DropdownMenuItem>
			</DropdownMenuContent>
		</DropdownMenu>
	);
}

// src/routes/admin/cabins/cabins-table-actions.svelte
<script lang="ts">
	import {
		ClipboardCopyIcon,
		CopyIcon,
		EllipsisIcon,
		PencilRulerIcon,
		Trash2Icon
	} from '@lucide/svelte';

	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import { Button } from '$lib/components/ui/button';
	import { toast } from 'svelte-sonner';

	let { id }: { id: string } = $props();

	function handleCopyId() {
		navigator.clipboard.writeText(id);
		toast('ID Copied to clipboard');
	}
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger>
		{#snippet child({ props })}
			<Button
				{...props}
				variant="ghost"
				size="icon"
				class="relative size-8 cursor-pointer p-0"
			>
				<span class="sr-only">Open Menu</span>
				<EllipsisIcon />
			</Button>
		{/snippet}
	</DropdownMenu.Trigger>

	<DropdownMenu.Content align="end">
		<DropdownMenu.Group>
			<DropdownMenu.Label>Actions</DropdownMenu.Label>

			<DropdownMenu.Separator />

			<DropdownMenu.Item onclick={handleCopyId}>
				<CopyIcon />
				Copy Cabin ID
			</DropdownMenu.Item>

			<DropdownMenu.Item>
				<ClipboardCopyIcon />
				Duplicate Cabin
			</DropdownMenu.Item>

			<DropdownMenu.Item>
				<PencilRulerIcon />
				Edit Cabin
			</DropdownMenu.Item>

			<DropdownMenu.Item class="text-destructive">
				<Trash2Icon class="text-destructive" />
				Delete Cabin
			</DropdownMenu.Item>
		</DropdownMenu.Group>
	</DropdownMenu.Content>
</DropdownMenu.Root>
