// src/features/auth/components/sign-in-form.tsx
import React from 'react'

import { useForm } from '@tanstack/react-form'
import { useNavigate } from '@tanstack/react-router'

import { EyeIcon, EyeOffIcon } from 'lucide-react'
import { toast } from 'sonner'
import { z } from 'zod'

import { Button } from '@/components/ui/button'
import { Field, FieldError, FieldGroup, FieldLabel, FieldSet } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from '@/components/ui/input-group'
import { Spinner } from '@/components/ui/spinner'
import { DEFAULT_REDIRECT_AFTER_LOGIN } from '@/config/constants'
import { authClient } from '@/lib/auth-client'

const SignInSchema = z.object({
    email: z.email('Please enter a valid email address'),
    password: z.string().min(8, 'Password must be at least 8 characters'),
})

export function SignInForm() {
    const [showPassword, setShowPassword] = React.useState<boolean>(false)
    const [state, setState] = React.useState<'idle' | 'loading' | 'success' | 'error'>('idle')
    const navigate = useNavigate()

    const form = useForm({
        defaultValues: {
            email: '',
            password: '',
        },
        validators: {
            onChangeAsync: SignInSchema,
            onChangeAsyncDebounceMs: 500,
        },
        onSubmit: async ({ value }) => {
            await authClient.signIn.email(
                { email: value.email, password: value.password },
                {
                    onRequest: () => {
                        setState('loading')
                    },
                    onSuccess: () => {
                        setState('success')
                        toast.success('You have successfully logged in')
                        navigate({ to: DEFAULT_REDIRECT_AFTER_LOGIN })
                    },
                    onError: (ctx) => {
                        //   TODO: Improve error handling
                        console.error(ctx.error)
                        setState('error')
                        toast.error('Something went wrong')
                    },
                },
            )
        },
    })

    return (
        <form
            onSubmit={(e) => {
                e.preventDefault()
                e.stopPropagation()

                void form.handleSubmit()
            }}
            className="space-y-6"
        >
            <FieldSet>
                <FieldGroup className="gap-3">
                    <form.Field
                        name="email"
                        children={(field) => (
                            <Field data-invalid={field.state.meta.errors.length > 0}>
                                <FieldLabel htmlFor="email">Tell us your email address</FieldLabel>
                                <Input
                                    id="email"
                                    type="email"
                                    placeholder="iamawesome@email.com"
                                    aria-invalid={field.state.meta.errors.length > 0}
                                    onChange={(e) => field.handleChange(e.target.value)}
                                />
                                {field.state.meta.errors?.map((error) => (
                                    <FieldError key={error?.message}>{error?.message}</FieldError>
                                ))}
                            </Field>
                        )}
                    />

                    <form.Field
                        name="password"
                        children={(field) => (
                            <Field data-invalid={field.state.meta.errors.length > 0}>
                                <FieldLabel htmlFor="password">Choose a password</FieldLabel>
                                <InputGroup>
                                    <InputGroupInput
                                        type={showPassword ? 'text' : 'password'}
                                        placeholder="••••••••"
                                        onChange={(e) => field.handleChange(e.target.value)}
                                        aria-invalid={field.state.meta.errors.length > 0}
                                    />
                                    <InputGroupAddon align="inline-end">
                                        <InputGroupButton
                                            aria-label="Show password"
                                            title="Show password"
                                            size="icon-xs"
                                            tabIndex={-1}
                                            onClick={() => {
                                                setShowPassword((prev) => !prev)
                                            }}
                                        >
                                            {showPassword ? <EyeOffIcon /> : <EyeIcon />}
                                        </InputGroupButton>
                                    </InputGroupAddon>
                                </InputGroup>
                                {field.state.meta.errors?.map((error) => (
                                    <FieldError key={error?.message}>{error?.message}</FieldError>
                                ))}
                            </Field>
                        )}
                    />
                </FieldGroup>
            </FieldSet>

            {state === 'error' && <p className="text-destructive text-sm">Something went wrong. Please try again.</p>}

            <Button type="submit" className="w-full" disabled={state === 'loading'} onClick={() => form.handleSubmit()}>
                {state === 'loading' && <Spinner />}
                {state === 'loading' ? 'Signing In...' : 'Sign In'}
            </Button>
        </form>
    )
}

// src/routes/(auth)/sign-in/sign-in-form.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { CircleAlertIcon, EyeIcon, EyeOffIcon } from '@lucide/svelte';
	import { createForm } from '@tanstack/svelte-form';

	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { authClient } from '$lib/auth-client';
	import { Button } from '$lib/components/ui/button';
	import { Field, FieldError, FieldGroup, FieldLabel, FieldSet } from '$lib/components/ui/field';
	import {
		InputGroup,
		InputGroupAddon,
		InputGroupButton,
		InputGroupInput
	} from '$lib/components/ui/input-group';
	import Input from '$lib/components/ui/input/input.svelte';
	import { Spinner } from '$lib/components/ui/spinner';

	import { SignInSchema } from './schema';

	let showPassword = $state<boolean>(false);
	let status = $state<'idle' | 'loading' | 'success' | 'error'>('idle');
	let errorMessage = $state<string | null>(null);

	const form = createForm(() => ({
		defaultValues: {
			email: '',
			password: ''
		},
		validators: {
			onChangeAsync: SignInSchema,
			onChangeAsyncDebounceMs: 750
		},
		onSubmit: async ({ value }) => {
			await authClient.signIn.email(
				{
					email: value.email,
					password: value.password
				},
				{
					onRequest: () => {
						status = 'loading';
					},
					onSuccess: () => {
						status = 'success';
						toast.success('Signed in successfully');

						const redirect = page.url.searchParams.get('intended') ?? '/';
						goto(redirect);
					},
					onError: ({ error }) => {
						console.log('🚀 ~ err:', error);

						status = 'error';
						errorMessage = error.message;
					}
				}
			);
		}
	}));
</script>

<form
	onsubmit={(e) => {
		e.preventDefault();
		e.stopPropagation();

		form.handleSubmit();
	}}
	class="space-y-6"
>
	<FieldSet>
		<FieldGroup class="gap-3">
			<form.Field name="email">
				{#snippet children(field)}
					{@const hasErrors = field.state.meta.errors?.length > 0}
					<Field data-invalid={hasErrors}>
						<FieldLabel for={field.name}>Tell us your email address</FieldLabel>
						<Input
							id={field.name}
							type="email"
							placeholder="iamawesome@email.com"
							value={field.state.value}
							onblur={() => field.handleBlur()}
							oninput={(e: Event) => {
								const target = e.target as HTMLInputElement;
								field.handleChange(target.value);
							}}
							aria-invalid={hasErrors}
						/>
						{#if hasErrors}
							{#each field.state.meta.errors as error}
								<FieldError>{error?.message}</FieldError>
							{/each}
						{/if}
					</Field>
				{/snippet}
			</form.Field>

			<form.Field name="password">
				{#snippet children(field)}
					{@const hasErrors = field.state.meta.errors?.length > 0}
					<Field data-invalid={hasErrors}>
						<FieldLabel for={field.name}>Choose a secure password</FieldLabel>
						<InputGroup>
							<InputGroupInput
								type={showPassword ? 'text' : 'password'}
								placeholder="*********"
								value={field.state.value}
								onblur={() => field.handleBlur()}
								oninput={(e: Event) => {
									const target = e.target as HTMLInputElement;
									field.handleChange(target.value);
								}}
								aria-invalid={hasErrors}
							/>
							<InputGroupAddon align="inline-end">
								<InputGroupButton
									aria-label="Show password"
									title="show password"
									size="icon-xs"
									tabindex={-1}
									onclick={() => (showPassword = !showPassword)}
								>
									{#if showPassword}
										<EyeOffIcon />
									{:else}
										<EyeIcon />
									{/if}
								</InputGroupButton>
							</InputGroupAddon>
						</InputGroup>
						{#if hasErrors}
							{#each field.state.meta.errors as error}
								<FieldError>{error?.message}</FieldError>
							{/each}
						{/if}
					</Field>
				{/snippet}
			</form.Field>
		</FieldGroup>
	</FieldSet>

	{#if errorMessage}
		<div class="rounded-lg border border-destructive bg-destructive/10 p-2">
			<div class="flex items-start gap-3">
				<div class="rounded-full bg-destructive/15 p-1.5">
					<CircleAlertIcon class="size-4 text-destructive" />
				</div>
				<div class="flex-1 space-y-1 text-sm">
					<h3 class="font-semibold text-destructive">Oops! Something went wrong</h3>
					<p class="text-destructive/90">{errorMessage}</p>
				</div>
			</div>
		</div>
	{/if}

	<form.Subscribe
		selector={(state) => ({
			canSubmit: state.canSubmit,
			isSubmitting: state.isSubmitting
		})}
	>
		{#snippet children({ canSubmit, isSubmitting })}
			<Button type="submit" disabled={!canSubmit} class="w-full">
				{#if isSubmitting}
					<Spinner />
				{/if}
				{isSubmitting ? 'Signing in...' : 'Sign In'}
			</Button>
		{/snippet}
	</form.Subscribe>
</form>
