// src/routes/dashboard/cabins/[id]/edit/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import type { PageData } from './$types';
	import { ChevronLeftIcon } from 'lucide-svelte';

	import Button from '$lib/components/ui/button/button.svelte';
	import { goto } from '$app/navigation';

	export let data: PageData;
</script>

<svelte:head>
	<title>Edit Cabin | HBS</title>
</svelte:head>

<Button variant="outline" size="icon" class="mb-3" on:click={() => goto('/dashboard/cabins/' + $page.params.id)}>
	<ChevronLeftIcon class="size-6" />
</Button>
<h1 class="text-3xl font-bold mb-6">Edit Cabin</h1>

<p>Editing Cabin with ID: {data.cabin.id}</p>

// src/app/admin/cabins/[id]/edit/page.tsx
import Link from 'next/link';
import { ChevronLeftIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { getCabinDetails } from '@/data/cabins';
import { CabinForm } from '../../cabin-form';

export default async function EditCabinPage({ params }: { params: { id: string } }) {
	const cabin = await getCabinDetails(params.id);

	return (
		<>
			<div className="space-y-2">
				<Button variant="outline" size="icon" asChild>
					<Link href="/admin/cabins">
						<ChevronLeftIcon className="size-4" />
					</Link>
				</Button>
				<h1 className="text-3xl font-semibold tracking-wide">All Cabins: {params.id}</h1>
			</div>

			<div className="mb-8 mt-6">
				<CabinForm cabin={cabin} />
			</div>
		</>
	);
}
