// src/app/(dashboard)/cabins/page.tsx
import { PlusIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { CabinsTable } from './cabins-table';

export default async function CabinsPage() {
	return (
		<>
			<div className="flex items-center justify-between">
				<h1 className="text-3xl font-semibold tracking-wide">All Cabins</h1>
				<Button size="sm">
					<PlusIcon size={16} className="mr-2" />
					Add Cabin
				</Button>
			</div>

			<CabinsTable />
		</>
	);
}

// src/routes/(dashboard)/cabins/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button/button.svelte';
	import { PlusIcon } from 'lucide-svelte';
	import type { PageData } from './$types';
	import CabinsTable from './cabins-table.svelte';

	export let data: PageData;
</script>

<svelte:head>
	<title>Cabins</title>
</svelte:head>

<div class="mb-4 flex items-center">
	<h1 class="text-3xl font-bold tracking-wide">All Cabins</h1>
	<Button href="cabins/add" class="ml-auto">
		<PlusIcon class="mr-2 size-4" />
		Add Cabin
	</Button>
</div>

<CabinsTable data={data.cabins} />
