// src/lib/components/admin/admin-sidebar.svelte
<script lang="ts">
	import {
		CalendarIcon,
		FlameKindlingIcon,
		HouseIcon,
		Settings2Icon,
		SettingsIcon,
		UsersIcon
	} from '@lucide/svelte';

	import { page } from '$app/state';
	import logo from '$lib/assets/logo.webp';
	import * as Sidebar from '$lib/components/ui/sidebar';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import { useSidebar } from '$lib/components/ui/sidebar';
	import { cn } from '$lib/utils';

	const sidebar = useSidebar();

	const items = [
		{
			title: 'Home',
			href: '/admin',
			icon: HouseIcon
		},
		{
			title: 'Cabins',
			href: '/admin/cabins',
			icon: FlameKindlingIcon
		},
		{
			title: 'Bookings',
			href: '/admin/bookings',
			icon: CalendarIcon
		},
		{
			title: 'Users',
			href: '/admin/users',
			icon: UsersIcon
		}
	];
</script>

<Sidebar.Root variant="sidebar" collapsible="icon" class="relative">
	<Sidebar.Header class={cn(sidebar.open && 'p-4')}>
		<div class="flex items-center gap-3">
			{#if sidebar.open}
				<img class="rounded-full" src={logo} alt="logo" width="35" height="35" />
				<div>
					<p class="text-sm font-bold">The Wild Oasis</p>
					<p class="text-xs text-muted-foreground">Admin Panel</p>
				</div>
			{:else}
				<img class="rounded-full" src={logo} alt="logo" width="30" height="30" />
			{/if}
		</div>
	</Sidebar.Header>

	<Sidebar.Content class="mt-6">
		<Sidebar.Group>
			<Sidebar.GroupLabel>Application</Sidebar.GroupLabel>
			<Sidebar.GroupContent>
				<Sidebar.Menu class="space-y-2.5">
					{#each items as item (item.href)}
						<Sidebar.MenuItem>
							<Sidebar.MenuButton isActive={page.url.pathname === item.href}>
								{#snippet child({ props })}
									<a href={item.href} {...props}>
										{#if sidebar.open}
											<item.icon class="size-4" />
											<span>{item.title}</span>
										{:else}
											<Tooltip.Provider>
												<Tooltip.Root>
													<Tooltip.Trigger>
														<item.icon class="size-4" />
													</Tooltip.Trigger>
													<Tooltip.Content side="right">
														<p>{item.title}</p>
													</Tooltip.Content>
												</Tooltip.Root>
											</Tooltip.Provider>
										{/if}
									</a>
								{/snippet}
							</Sidebar.MenuButton>
							{#if item.title === 'Bookings'}
								<Sidebar.MenuBadge>3</Sidebar.MenuBadge>
							{/if}
						</Sidebar.MenuItem>
					{/each}
				</Sidebar.Menu>
			</Sidebar.GroupContent>
		</Sidebar.Group>
	</Sidebar.Content>

	<Sidebar.Footer>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton>
					{#snippet child({ props })}
						<a href="/admin/settings" {...props}>
							{#if sidebar.open}
								<SettingsIcon class="size-4" />
								<span>Settings</span>
							{:else}
								<Tooltip.Provider>
									<Tooltip.Root>
										<Tooltip.Trigger>
											<SettingsIcon class="size-4" />
										</Tooltip.Trigger>
										<Tooltip.Content side="right">
											<p>Settings</p>
										</Tooltip.Content>
									</Tooltip.Root>
								</Tooltip.Provider>
							{/if}
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Footer>
</Sidebar.Root>

// features/layout/admin-sidebar.tsx
'use client';

import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

import {
    CalendarDaysIcon,
    FlagIcon,
    HouseIcon,
    MailIcon,
    MessageSquareIcon,
    SettingsIcon,
    TreePineIcon,
    UsersIcon,
} from 'lucide-react';

import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarGroup,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import { LogoutMenuButton } from '@/features/layout/logout-menu-button';
import { APP_ROUTES } from '@/lib/routes';

const NAV_ITEMS = [
    { label: 'Home', href: APP_ROUTES.ADMIN, icon: HouseIcon },
    { label: 'Bookings', href: APP_ROUTES.ADMIN_BOOKINGS, icon: CalendarDaysIcon },
    { label: 'Cabins', href: APP_ROUTES.ADMIN_CABINS, icon: TreePineIcon },
    { label: 'Messages', href: APP_ROUTES.ADMIN_MESSAGES, icon: MessageSquareIcon },
    { label: 'Users', href: APP_ROUTES.ADMIN_USERS, icon: UsersIcon },
    { label: 'Subscribers', href: APP_ROUTES.ADMIN_SUBSCRIBERS, icon: MailIcon },
    { label: 'Feature Flags', href: APP_ROUTES.ADMIN_FEATURE_FLAGS, icon: FlagIcon },
    { label: 'Settings', href: APP_ROUTES.ADMIN_SETTINGS, icon: SettingsIcon },
] as const;

export function AdminSidebar() {
    const pathname = usePathname();

    return (
        <Sidebar>
            <SidebarHeader>
                <Link
                    href={APP_ROUTES.HOME}
                    className='flex items-center gap-2 px-2 py-1'
                    aria-label='The Wild Oasis home'
                >
                    <Image src='/assets/logo.webp' alt='' width={28} height={20} />
                    <span className='font-heading text-sm font-medium'>The Wild Oasis</span>
                </Link>
            </SidebarHeader>
            <SidebarContent>
                <SidebarGroup>
                    <SidebarMenu>
                        {NAV_ITEMS.map((item) => (
                            <SidebarMenuItem key={item.href}>
                                <SidebarMenuButton
                                    render={<Link href={item.href} />}
                                    isActive={pathname === item.href}
                                >
                                    <item.icon />
                                    <span>{item.label}</span>
                                </SidebarMenuButton>
                            </SidebarMenuItem>
                        ))}
                    </SidebarMenu>
                </SidebarGroup>
            </SidebarContent>
            <SidebarFooter>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <LogoutMenuButton />
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarFooter>
        </Sidebar>
    );
}
