// app/components/layout/sidebar.tsx
import { NavLink, useLocation } from '@remix-run/react';
import { HomeIcon, CalendarIcon, FlameKindlingIcon, UsersIcon, SettingsIcon } from 'lucide-react';

import logoWhite from '~/assets/logo-light.png';
import { cn } from '~/lib/utils';

const NAV_LINKS = [
	{ label: 'Home', to: '/dashboard', current: true, icon: <HomeIcon className="size-4" />, exact: true },
	{
		label: 'Bookings',
		to: '/dashboard/bookings',
		current: false,
		icon: <CalendarIcon className="size-4" />,
		exact: false,
	},
	{
		label: 'Cabins',
		to: '/dashboard/cabins',
		current: false,
		icon: <FlameKindlingIcon className="size-4" />,
		exact: false,
	},
	{ label: 'Users', to: '/dashboard/users', current: false, icon: <UsersIcon className="size-4" />, exact: false },
	{
		label: 'Settings',
		to: '/dashboard/settings',
		current: false,
		icon: <SettingsIcon className="size-4" />,
		exact: false,
	},
];

function isActiveLink(pathname: string, to: string, isExact = false) {
	if (isExact) return pathname === to;

	return pathname === to || pathname.startsWith(to);
}

export function AppSidebar() {
	const location = useLocation();

	return (
		<aside className="row-span-full border-r">
			<div>
				<img src={logoWhite} alt="logo" className="mx-auto my-8 w-20" />
			</div>

			{/* Navigation Links */}
			<nav className="flex flex-col space-y-2 px-4">
				{NAV_LINKS.map(({ label, to, icon, exact }) => (
					<NavLink
						key={label}
						to={to}
						className={() => {
							const isCurrent = isActiveLink(location.pathname, to, exact);

							return cn('flex items-center gap-3 rounded-md px-4 py-3 text-sm', {
								'bg-gray-200 font-semibold text-primary': isCurrent,
								'hover:bg-gray-200': !isCurrent,
							});
						}}
					>
						{icon}
						<span className="font-light">{label}</span>
					</NavLink>
				))}
			</nav>
		</aside>
	);
}

// src/lib/components/sidebar.svelte
<script lang="ts">
	import { CalendarDaysIcon, HomeIcon, SettingsIcon, TreesIcon, UsersIcon } from 'lucide-svelte';
	import { page } from '$app/stores';

	import NavLink from './nav-link.svelte';
	import { cn } from '$lib/utils';

	// const links = [
	// 	{ id: 0, name: 'Dashboard', href: '/dashboard', icon: HomeIcon },
	// 	{ id: 1, name: 'Bookings', href: '/bookings', icon: CalendarDaysIcon },
	// 	{ id: 2, name: 'Cabins', href: '/cabins', icon: TreesIcon },
	// 	{ id: 3, name: 'Users', href: '/users', icon: UsersIcon },
	// 	{ id: 4, name: 'Settings', href: '/settings', icon: SettingsIcon }
	// ];

	$: pathname = new URL($page.url).pathname;
</script>

<aside class="row-span-full flex flex-col gap-14 border-r border-neutral-100 bg-white p-4">
	<a href="/dashboard">
		<div class="flex justify-center">
			<img src="/logo-light.png" alt="logo" width={200} height={200} class="h-16 w-auto" />
		</div>
	</a>

	<!-- Sidebar Navigation -->
	<nav>
		<ul class="flex flex-col gap-3">
			<NavLink href="/dashboard" name="Dashboard">
				<HomeIcon
					class={cn(
						'h-5 w-5 opacity-70 group-hover:text-primary',
						pathname === '/dashboard' && 'text-primary opacity-100'
					)}
				/>
			</NavLink>
			<NavLink href="/bookings" name="Bookins">
				<CalendarDaysIcon
					class={cn(
						'h-5 w-5 opacity-70 group-hover:text-primary',
						pathname === '/bookings' && 'text-primary opacity-100'
					)}
				/>
			</NavLink>
			<NavLink href="/cabins" name="Cabins">
				<TreesIcon
					class={cn(
						'h-5 w-5 opacity-70 group-hover:text-primary',
						pathname === '/cabins' && 'text-primary opacity-100'
					)}
				/>
			</NavLink>
			<NavLink href="/users" name="Users">
				<UsersIcon
					class={cn(
						'h-5 w-5 opacity-70 group-hover:text-primary',
						pathname === '/users' && 'text-primary opacity-100'
					)}
				/>
			</NavLink>
			<NavLink href="/settings" name="Settings">
				<SettingsIcon
					class={cn(
						'h-5 w-5 opacity-70 group-hover:text-primary',
						pathname === '/settings' && 'text-primary opacity-100'
					)}
				/>
			</NavLink>
		</ul>
	</nav>
</aside>
