// src/app/dashboard/cabins/page.tsx
import { Suspense } from 'react';

import { CabinsTable } from './_components/cabins-table';

export default async function CabinsPage() {
	return (
		<div>
			<h1 className="text-2xl font-bold">Cabins</h1>

			<div>
				<Suspense fallback={<div>Loading...</div>}>
					<CabinsTable />
				</Suspense>
			</div>
		</div>
	);
}

// src/routes/cabins/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	import CabinsTable from '$lib/components/cabins/cabins-table.svelte';

	export let data: PageData;
</script>

<svelte:head>
	<title>Cabins | HBS</title>
</svelte:head>

<h1 class="text-3xl font-bold mb-6">All Cabins</h1>

<CabinsTable cabins={data.cabins} />
