// src/routes/dashboard/cabins/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import type { PageData } from './$types';
	import { ChevronLeftIcon, PencilIcon } from 'lucide-svelte';

	import Button from '$lib/components/ui/button/button.svelte';

	export let data: PageData;
</script>

<svelte:head>
	<title>Cabin Details | HBS</title>
</svelte:head>

<div class="flex items-center justify-between">
	<div>
		<Button variant="outline" size="icon" class="mb-3" on:click={() => goto('/dashboard/cabins')}>
			<ChevronLeftIcon class="size-6" />
		</Button>
		<h1 class="text-3xl font-bold mb-6">Cabin Details</h1>
	</div>

	<Button on:click={() => goto(`/dashboard/cabins/${$page.params.id}/edit`)}>
		<PencilIcon class="size-4 mr-2" />
		Edit Cabin
	</Button>
</div>

// _old/src/app/admin/cabins/[id]/page.tsx
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { PencilIcon } from 'lucide-react';
import { cookies } from 'next/headers';

import { Button } from '@/components/ui/button';
import { getCabinDetails } from '@/data/cabins';

type CabinDetailsPageProps = {
	params: {
		id: string;
	};
};

export default async function CabinDetailsPage({ params }: CabinDetailsPageProps) {
	const cabin = await getCabinDetails(params.id);
	const success = cookies().get('cabinCreated');
	const updated = cookies().get('cabinUpdated');

	if (!cabin) redirect('/cabins');

	return (
		<>
			<div className="flex items-center justify-between">
				<div className="flex items-baseline gap-3">
					<h1 className="text-3xl font-semibold tracking-wide">Cabin Details</h1>
					{success && (
						<>
							<span> -</span>
							<p className="animate-bounce font-semibold text-green-400">New Cabin</p>
						</>
					)}

					{updated && (
						<>
							<span> -</span>
							<p className="animate-bounce font-semibold text-green-400">Cabin Updated</p>
						</>
					)}
				</div>

				<Button size="sm" asChild>
					<Link href={`${params.id}/edit`}>
						<PencilIcon size={16} className="mr-2" />
						Edit Cabin
					</Link>
				</Button>
			</div>

			<pre>{JSON.stringify({ id: cabin.id, name: cabin.name }, null, 2)}</pre>
		</>
	);
}
